services:
  ollama:
    build:
      context: ollama-elyza-docker
      dockerfile: Dockerfile.cpu
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS="*"

  whisper:
    build:
      context: whisper.cpp-docker
      dockerfile: Dockerfile.cpu
    container_name: whisper
    ports:
      - "8080:8080"

  style-bert-vits2:
    build:
      context: sbv2-docker
      dockerfile: Dockerfile.cpu
    container_name: style-bert-vits2-app
    volumes:
      - ./sbv2-docker/model_assets:/app/model_assets
    ports:
      - "8000:7860"
      - "5000:5000"
      - "6006:6006"
    restart: unless-stopped
    command: python server_fastapi.py
