services:
  style-bert-vits2:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: style-bert-vits2-app
    volumes:
      - ./model_assets:/app/model_assets
    ports:
      - "8000:7860"
      - "5000:5000"
      - "6006:6006"
    restart: unless-stopped
    command: python server_fastapi.py --cpu
